replicaCount: 3

container:
  name: webapp
  port: 80

image:
  repository: your-webapp-image
  tag: latest

env:
  ENV_VAR_NAME: "Value"

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

livenessProbe:
  path: /health
  port: 80

readinessProbe:
  path: /health
  port: 80

volumes:
  - name: config-vol
    mountPath: /etc/config
    configMap:
      name: log-config
      items:
        - key: log_level
          path: log_level

service:
  type: ClusterIP
  port: 80


ingress:
  hosts:
  - host: example.com
    paths:
    - path: /

autoscaling:
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 75